--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Clientes; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public."Clientes" (
    "IdCliente" integer NOT NULL,
    "NomeCliente" text NOT NULL,
    "EnderecoCliente" text NOT NULL,
    "TelefoneCliente" text NOT NULL,
    "EmailCliente" text NOT NULL,
    "DataCadastroCliente" timestamp with time zone NOT NULL
);


ALTER TABLE public."Clientes" OWNER TO sa;

--
-- Name: Clientes_IdCliente_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public."Clientes" ALTER COLUMN "IdCliente" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clientes_IdCliente_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Produtos; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public."Produtos" (
    "IdProduto" integer NOT NULL,
    "NomeProduto" text NOT NULL,
    "DescricaoProduto" text NOT NULL,
    "PrecoProduto" numeric NOT NULL,
    "EstoqueProduto" integer NOT NULL,
    "DataCadastroProduto" timestamp with time zone NOT NULL
);


ALTER TABLE public."Produtos" OWNER TO sa;

--
-- Name: Produtos_IdProduto_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public."Produtos" ALTER COLUMN "IdProduto" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Produtos_IdProduto_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vendas; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public."Vendas" (
    "IdVenda" integer NOT NULL,
    "IdCliente" integer,
    "ClientesIdCliente" integer NOT NULL,
    "IdProduto" integer,
    "ProdutoIdProduto" integer NOT NULL,
    "QuantidadeVenda" integer NOT NULL,
    "DescricaoVenda" text NOT NULL
);


ALTER TABLE public."Vendas" OWNER TO sa;

--
-- Name: Vendas_IdVenda_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public."Vendas" ALTER COLUMN "IdVenda" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vendas_IdVenda_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO sa;

--
-- Name: Clientes PK_Clientes; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public."Clientes"
    ADD CONSTRAINT "PK_Clientes" PRIMARY KEY ("IdCliente");


--
-- Name: Produtos PK_Produtos; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public."Produtos"
    ADD CONSTRAINT "PK_Produtos" PRIMARY KEY ("IdProduto");


--
-- Name: Vendas PK_Vendas; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public."Vendas"
    ADD CONSTRAINT "PK_Vendas" PRIMARY KEY ("IdVenda");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Vendas_ClientesIdCliente; Type: INDEX; Schema: public; Owner: sa
--

CREATE INDEX "IX_Vendas_ClientesIdCliente" ON public."Vendas" USING btree ("ClientesIdCliente");


--
-- Name: IX_Vendas_ProdutoIdProduto; Type: INDEX; Schema: public; Owner: sa
--

CREATE INDEX "IX_Vendas_ProdutoIdProduto" ON public."Vendas" USING btree ("ProdutoIdProduto");


--
-- Name: Vendas FK_Vendas_Clientes_ClientesIdCliente; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public."Vendas"
    ADD CONSTRAINT "FK_Vendas_Clientes_ClientesIdCliente" FOREIGN KEY ("ClientesIdCliente") REFERENCES public."Clientes"("IdCliente") ON DELETE CASCADE;


--
-- Name: Vendas FK_Vendas_Produtos_ProdutoIdProduto; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public."Vendas"
    ADD CONSTRAINT "FK_Vendas_Produtos_ProdutoIdProduto" FOREIGN KEY ("ProdutoIdProduto") REFERENCES public."Produtos"("IdProduto") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

