// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TkmStore.DAL.Model;

#nullable disable

namespace TkmStore.DAL.Migrations
{
    [DbContext(typeof(TkmDBContext))]
    [Migration("20240629193733_TkmDB-V1")]
    partial class TkmDBV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TkmStore.DAL.Model.Entity.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<DateTime>("DataCadastroCliente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnderecoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TkmStore.DAL.Model.Entity.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduto"));

                    b.Property<DateTime>("DataCadastroProduto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstoqueProduto")
                        .HasColumnType("integer");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoProduto")
                        .HasColumnType("numeric");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("TkmStore.DAL.Model.Entity.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVenda"));

                    b.Property<int>("ClientesIdCliente")
                        .HasColumnType("integer");

                    b.Property<string>("DescricaoVenda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProduto")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoIdProduto")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeVenda")
                        .HasColumnType("integer");

                    b.HasKey("IdVenda");

                    b.HasIndex("ClientesIdCliente");

                    b.HasIndex("ProdutoIdProduto");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("TkmStore.DAL.Model.Entity.Venda", b =>
                {
                    b.HasOne("TkmStore.DAL.Model.Entity.Cliente", "Clientes")
                        .WithMany("Vendas")
                        .HasForeignKey("ClientesIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TkmStore.DAL.Model.Entity.Produto", "Produto")
                        .WithMany("Vendas")
                        .HasForeignKey("ProdutoIdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TkmStore.DAL.Model.Entity.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("TkmStore.DAL.Model.Entity.Produto", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
